### PR TITLE
Enhancements

### PR DESCRIPTION
**Pull request by Phil-Friderici**

### CODE REVIEW

**Comment by virus2500** [comment]
Hi Phil, 

i looked through your pull requests, unfortunatly it seems like trlinkin is inactive for quite some time.... 

Would you be willing to "fully" fork this repo and upload "your own" fork to the forge?

thanks and br

**Comment by Phil-Friderici** [comment]
Hi Michael,

we are thinking of forking away too. We already have a [fork](https://github.com/kodguru/puppet-nsswitch) and I have just copied the PRs to it. I guess there is a high chance that we will merge them soon (@anders-larsson what do you think?) . But we will not put them on the forge as we don't use the forge anyway.

Phil

**Comment by virus2500** [comment]
Hi Phil,

thanks for the info! :)

Guess i'll need to look into how to set up a metadata.json with an dependency on a github project then :)

br

**Comment by anders-larsson** [comment]
Yeah, until trlinkin becomes active again I suspect we'll have to maintain a fork. I have reviewed the pull requests btw. :)

**Comment by Phil-Friderici** [comment]
Thanks @anders-larsson for reviewing my PR. I have merged them and created the new release `v3.0.0-forked` which do include them.
@virus2500 feel free to use our fork at https://github.com/kodguru/puppet-nsswitch we might add more changes and will create new releases for them. If you have something in mind, send a PR :)

**Comment by virus2500** [comment]
Thanks for the update/sharing. :)

**Comment by virus2500** [comment]
Hi, 

thought i'd share this with you as it might be interesting for you as well.

I just noticed that it seems like voxpupuli officially took over. 

https://forge.puppet.com/modules/puppet/nsswitch/readme and
https://github.com/voxpupuli/puppet-nsswitch

**Pull request merged**
